/* Generated By:JavaCC: Do not edit this line. QuantumAssemblyConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QuantumAssemblyConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int HADAMARD = 5;
  /** RegularExpression Id. */
  int PHASE = 6;
  /** RegularExpression Id. */
  int INDEN = 7;
  /** RegularExpression Id. */
  int CNOT = 8;
  /** RegularExpression Id. */
  int NOT = 9;
  /** RegularExpression Id. */
  int INIT = 10;
  /** RegularExpression Id. */
  int APP = 11;
  /** RegularExpression Id. */
  int SEL = 12;
  /** RegularExpression Id. */
  int CON = 13;
  /** RegularExpression Id. */
  int TEN = 14;
  /** RegularExpression Id. */
  int INV = 15;
  /** RegularExpression Id. */
  int MEAS = 16;
  /** RegularExpression Id. */
  int LBRACKET = 17;
  /** RegularExpression Id. */
  int RBRACKET = 18;
  /** RegularExpression Id. */
  int SEMICOLON = 19;
  /** RegularExpression Id. */
  int TWODOT = 20;
  /** RegularExpression Id. */
  int COMMA = 21;
  /** RegularExpression Id. */
  int CHAR = 22;
  /** RegularExpression Id. */
  int UPPER = 23;
  /** RegularExpression Id. */
  int LOWER = 24;
  /** RegularExpression Id. */
  int IDENTIFIER = 25;
  /** RegularExpression Id. */
  int QUBIT = 26;
  /** RegularExpression Id. */
  int NUMBER = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"H\"",
    "\"PHASE\"",
    "\"IDENTITY\"",
    "\"CNOT\"",
    "\"NOT\"",
    "\"INITIALIZE\"",
    "\"APPLY\"",
    "\"SELECT\"",
    "\"CONCAT\"",
    "\"TENSOR\"",
    "\"INVERSE\"",
    "\"MEASURE\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "<CHAR>",
    "<UPPER>",
    "<LOWER>",
    "<IDENTIFIER>",
    "<QUBIT>",
    "<NUMBER>",
  };

}
